services:

  db:
    image: postgres:16
    container_name: financas_ibf_db
    env_file:
      - ./backend/.env.confdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - financas_network

  backend:
    build: ./backend
    container_name: financas_backend
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    restart: always
    networks:
      - financas_network

  frontend:
    build:
      context: ./frontend/Dockerfile
    container_name: financas_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - financas_network

volumes:
  pgdata:

networks:
  financas_network:
    driver: bridge